### ISSUE TITLE
找到个小bug

### ISSUE THREAD

**Issue by xingzhe1998** [cxapython/discogs_aio_spider#2]
![image](https://user-images.githubusercontent.com/49833015/78658455-c4f98500-78fc-11ea-95d3-347c47da508c.png)

最近在学习大佬写的代码
在装饰器和代码封装这一块，大佬逻辑写的很优美，应该是造过轮子的。
大佬玩的倒是挺飘逸挺开心的，不过可苦了我这个看代码的。
还有学到了一些python的新特性，涨了见识，并且一不小心就发现了自己有多lj
代码部分快看完了，但项目核心异步这一块一直没有深入了解过，不过这也算是个契机吧，
可以钻研一下，看以后能不能找到大佬写的其他bug
 :-)

**Comment by cxapython** [comment]
谢谢 已修复
